### ISSUE TITLE
关于我的误操作事件

### ISSUE THREAD

**Issue by Wybxc** [ThinkingStudios/ContingameIME#15]
## 事件经过

- 由于某些原因，此项目以我的项目的 fork 而存在
- 今天下午 16 时 20 分左右，我在浏览该项目时，不慎点击了Sync Fork按钮，导致主分支的最新提交遗失
- 16 时 24 分，我向维护者报告了这一情况，并开始寻找恢复方法
- 16 时 26 分，在 GitHub 事件日志中找到了被覆盖的提交哈希
- 16 时 47 分，主分支已恢复

希望此事件没有造成实质性损失，我对我的过失表示歉意。

## 一些建议

鉴于我并非此项目的长期维护者，可以考虑将此项目由 fork 转为一般的 repository。这样可以避免以后发生类似的意外情况，也可以改善项目在 GitHub 搜索中的曝光。

**Comment by TexBlock** [comment]
未来项目重写会重开仓库
