### ISSUE TITLE
1.20.1 Support

### ISSUE THREAD

**Issue by Wybxc** [ThinkingStudios/ContingameIME#3]
See https://github.com/Wybxc/IngameIME-Minecraft/releases/tag/1.20.1-Forge-Alpha1

**Comment by TexBlock** [comment]
我目前打算在fabric和forge同时支持1.20.x

I'm currently planning to support 1.20.x in both fabric and forge

**Comment by TexBlock** [comment]
目前在[InMinecraftIME](https://github.com/ThinkingStudios/InMinecraftIME)仓库内，等完全移植完会移动到此仓库。

It's currently in the [InMinecraftIME](https://github.com/ThinkingStudios/InMinecraftIME) repository, and will be moved to this repository when it's fully ported.

**Comment by Neboer** [comment]
可以将新版本上传到curseforge吗？
