### ISSUE TITLE
[Feature Request] FTB Quests任务编辑界面适配 | FTB Quests Task Editor Interface Adaptation

### ISSUE THREAD

**Issue by QianFuv** [ThinkingStudios/ContingameIME#4]
# 环境
Fabric 1.18.2
# 模组版本
ContingameIME 1.0.5和最新的FTB任务及其前置
# 截图
![TabTip_HlJt523ZQg](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/111696321/36f1bec6-d45e-4dfa-bba3-e74fa965a5db)
![TabTip_DkBnYfDSNC](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/111696321/d610ddd9-3617-4a45-94a4-f8d4605decf2)

**Comment by TexBlock** [comment]
try 1.0.6？

**Comment by QianFuv** [comment]
这是个问题吧
1.18.2的模组要在1.18.x版本上崩溃
![image](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/111696321/eddae27b-cb15-437e-9c32-1d4720daa13a)

**Comment by TexBlock** [comment]
草，我立刻修

**Comment by QianFuv** [comment]
1. 那个地方打字依然不行
2. 还有就是win11上全屏好像不能显示候选字的框框（有一个细节是窗口模式候选字的框不是模组的白色框而是系统输入法自带的候选字选框）

**Comment by QianFuv** [comment]
类似这样 ↓
![image](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/111696321/79178490-c66b-4c30-b345-b8d812b37a19)

**Comment by TexBlock** [comment]
> 2. 还有就是win11上全屏好像不能显示候选字的框框（有一个细节是窗口模式候选字的框不是模组的白色框而是系统输入法自带的候选字选框）

在窗口模式下，显示的就是系统输入法的候选栏

**Comment by QianFuv** [comment]
那情况就是全屏模式莫得候选栏

**Comment by QianFuv** [comment]
更新fabric loader为0.14.22后全屏能正常显示候选栏
但是ftb任务的问题依旧不行

**Comment by TexBlock** [comment]
> 更新fabric loader为0.14.22后全屏能正常显示候选栏 但是ftb任务的问题依旧不行

到时候我mixin一下吧（

**Comment by QianFuv** [comment]
ftb任务编辑不显示候选栏也是个老问题了，不知道为啥没人反馈（

**Comment by QianFuv** [comment]
补充：全屏显示候选框在win11上（仅在我的设备上测试）还是不稳定 原因不明

**Comment by TexBlock** [comment]
> 补充：全屏显示候选框在win11上（仅在我的设备上测试）还是不稳定 原因不明

Windows版本号？

**Comment by QianFuv** [comment]
目前最新的dev通道测试版
但是我感觉这个问题和win11版本没啥关系（（（可能

**Comment by Qian-F** [comment]
问个题外话 大佬或者大佬能联系到有有偿移植高版本模组到1.18.2fabric的意愿的modder吗...本人目前整合包/服务器制作需要awa

**Comment by QianFuv** [comment]
关于全屏输入法，已经找到可复现的情况，详情见https://github.com/ThinkingStudios/IngameIME-ReInput/issues/6
