### ISSUE TITLE
[Bug][1.20.1]候选框出现文字阴影

### ISSUE THREAD

**Issue by Fiocher** [ThinkingStudios/ContingameIME#5]
与ModernUI一起使用时，输入法界面会产生强烈的文字阴影，导致文字难以辨识：
![1](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/82749343/8f30789c-864f-486a-8ed5-7d64125106d4)

关闭ModernUI设置里的使用阴影则恢复正常：
![2](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/82749343/88854e77-4b54-4f3e-bf4f-0a6254e3c780)

但这样会导致所有文字都没有阴影，在1.19.2中使用这两个模组不会有此现象。
不知道问题出在哪个上面..

游戏版本：1.20.1
模组版本：1.0.6-1.20.1-forge

**Comment by TexBlock** [comment]
~~暂时不会修复，你可以关闭modern ui 的字体阴影或者删除modern ui~~

将在下一个版本修复

**Comment by rlongdragon** [comment]
> 暂时不会修复，你可以关闭modern ui 的字体阴影或者删除modern ui

你好 我是繁體使用者，使用的輸入法是微軟輸入法。
我只有裝這個模組 還是有這個問題

**Comment by YoMonNPC** [comment]
仅安装此模组及前置，无论是否全屏、强制使用 Unicode 字体，在 Forge 与 Fabric 中文字阴影都会出现错误。

![屏幕截图 2023-09-03 152124](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/97231277/8fd3df99-8c4f-4bd9-99d4-cffbea4731c3)
![屏幕截图 2023-09-03 152136](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/97231277/c1e7ddf4-1eee-48e1-bc77-d9001417289f)
![IMG_20230903_151730](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/97231277/a725351d-2715-480a-b764-94334524dceb)
![IMG_20230903_151750](https://github.com/ThinkingStudios/IngameIME-ReInput/assets/97231277/549c8b1c-df57-49d5-8fda-8eaac05aca2c)

**Comment by ChromaPIE** [comment]
fabric可以用Sciophobia模组完全去除游戏内文字阴影

**Comment by TexBlock** [comment]
已在1.0.7修复
