### ISSUE TITLE
[NEXT] MOVE TO JAVA!

### ISSUE THREAD

**Issue by TexBlock** [ThinkingStudios/ContingameIME#8]
I thought kotlin was too obscure to maintain, so I chose to rewrite it in Java.
我认为kotlin过于晦涩难懂不方便继续维护，所以我选择在Java重写。

**Comment by AmarokIce** [comment]
It's too hard to changed most of the content, including the parts that use Kotlin's unique syntax, too dirty in Java syntax. 
对于大部分内容来说太过困难，包括Kotlin特有的语法在Java语法中描述，太过糟糕。

**Comment by TexBlock** [comment]
That's too bad.
